task: 'if_nerf'
gpus: [0]

parent_cfg: 'configs/zju_mocap_exp/latent_xyzc_313.yaml'

human: 17

train_dataset:
    data_root: 'data/AIST_mocap/d17'
    human: 'd17'
    ann_file: 'data/AIST_mocap/d17/annots.npy'
    split: 'train'

test_dataset:
    data_root: 'data/AIST_mocap/d17'
    human: 'd17'
    ann_file: 'data/AIST_mocap/d17/annots.npy'
    split: 'test'

# data options
num_train_frame: 300
H: 1080
W: 1920
white_bkg: True
