task: 'if_nerf'
gpus: [3]

parent_cfg: 'configs/zju_mocap_exp/latent_xyzc_313.yaml'

human: 19

train_dataset:
    data_root: 'data/AIST_mocap/d19'
    human: 'd19'
    ann_file: 'data/AIST_mocap/d19/annots.npy'
    split: 'train'

test_dataset:
    data_root: 'data/AIST_mocap/d19'
    human: 'd19'
    ann_file: 'data/AIST_mocap/d19/annots.npy'
    split: 'test'

# data options
num_train_frame: 300
H: 1080
W: 1920
white_bkgd: True
