task: 'zju_mocap'
subject: 'p393'
experiment: '300frame-ablation_skip3'


##############################################3
## Data Configuration

train:
  dataset_module: 'core.data.human_nerf.train'
  dataset: ['zju_393_train']

progress:
  dataset_module: 'core.data.human_nerf.train'
  dataset: ['zju_393_test']

movement:
  dataset_module: 'core.data.human_nerf.train'
  dataset: ['zju_393_test']

eval_freeview:
  dataset_module: 'core.data.human_nerf.freeview'
  dataset: ['zju_394_test_300frame']

tpose:
  dataset_module: 'core.data.human_nerf.tpose'
  dataset: ['zju_393_test']

eval_novel_view:
  dataset_module: 'core.data.human_nerf.eval'
  dataset: ['zju_393_test_300frame']


bgcolor: [0., 0., 0.]
resize_img_scale: 0.5

# reduce the size of patch from 32x32 to 20x20 to fit in a single gpu
patch:
  size: 20      # [Patch] size of patch
