task: 'AIST_mocap'
subject: 'd19'
experiment: '300frame-ablation_skip60'


##############################################3
## Data Configuration

train:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'AIST_d19_train'

progress:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'AIST_d19_test'

movement:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'AIST_d19_test'

freeview:
  dataset_module: 'core.data.human_nerf.freeview'
  dataset: 'AIST_d19_test'

tpose:
  dataset_module: 'core.data.human_nerf.tpose'
  dataset: 'AIST_d19_test'

bgcolor: [255., 255., 255.]
resize_img_scale: 0.5

# reduce the size of patch from 32x32 to 20x20 to fit in a single gpu
patch:
  size: 32      # [Patch] size of patch
